FROM jrdw-java-base:1.8.0_152
LABEL name="juip" build-date="20181025"
ADD libjava-1.0-SNAPSHOT-jar-with-dependencies.jar /opt
WORKDIR /opt/
CMD ["java", "-jar", "libjava-1.0-SNAPSHOT-jar-with-dependencies.jar"]
